# Generated by Django 4.0 on 2022-01-09 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='phones',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='phones',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store1.brands'),
        ),
    ]
