# Generated by Django 4.0 on 2022-01-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_brands_alter_phones_title_phones_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='price',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
